apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8761
    nodePort: 8761
  selector:
    app: eureka-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-service
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: eureka-service
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     tier: frontend
  template:
    metadata:
      labels:
        app: eureka-service
#      annotations:
#              scheduler.alpha.kubernetes.io/affinity: >
#                {
#                  "nodeAffinity": {
#                    "requiredDuringSchedulingIgnoredDuringExecution": {
#                      "nodeSelectorTerms": [
#                        {
#                          "matchExpressions": [
#                            {
#                              "key": "serviceGroup",
#                              "operator": "In",
#                              "values": ["eureka"]
#                            }
#                          ]
#                        }
#                      ]
#                    }
#                  }
#                }
    spec:
      nodeSelector:
        kubernetes.io/hostname: bigdata001
      containers:
      - name: eureka-service
        imagePullPolicy: Always
        image: 10.99.21.26/telecom-backend-services/eureka-service
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8761
        env:
          - name: EUREKA_SERVER_HOST_01
            value: "bigdata001"
#          - name: ZIPKIN_SERVER_HOST
#            value: "10.100.134.4"
#          - name: MONITOR_SERVER_HOST
#            value: "10.100.134.5"
      imagePullSecrets:
      - name: registrykey-m3-1

