server:
  port: ${EUREKA_SERVER_PORT:8000}  # 指定该Eureka实例的端口
eureka:
#  server:
#    enable-self-preservation: true           # 关闭自我保护模式（缺省为打开）
#    eviction-interval-timer-in-ms: 100000     # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
    registerWithEureka: false
    fetchRegistry: false